version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin@1234
      POSTGRES_DB: bookmark
    networks:
      - backend
networks:
  backend:
